
sudo: required
services: docker
language: generic

addons:
  artifacts: true

script:
    - curl -O https://raw.githubusercontent.com/cyber-dojo/commander/master/cyber-dojo
    - chmod +x cyber-dojo

    # Only build the cyber-dojo/system-tests image, the cyber-dojo/system-tests-environment
    # image can be pulled as it does not change very often
    - ./build.sh

    - ./cyber-dojo up

    # pull image used in tests
    - docker pull cyberdojofoundation/gcc_assert:latest

    - ./run_tests.sh

    # Remove the cyber-dojo script so it does not get uploaded as an artifact
    - rm -f cyber-dojo
