services: docker
language: bash

addons:
  artifacts: true

script:
    - curl -O https://raw.githubusercontent.com/cyber-dojo/commander/master/cyber-dojo
    - chmod +x cyber-dojo

    # Only build the cyber-dojo/system-tests image, the cyber-dojo/system-tests-environment
    # image can be pulled as it does not change very often
    - ./build.sh

    - ./build_new_ux_images.sh

    - URL=https://raw.githubusercontent.com/cyber-dojo/start-points-languages/master/languages_list_small
    - ./cyber-dojo start-point create small --list=${URL}
    - ./cyber-dojo up --languages=small

    # pull image used in tests
    - docker pull cyberdojofoundation/gcc_assert:latest

    - ./run_chrome_tests.sh
    - ./run_firefox_tests.sh

    # Remove the cyber-dojo script so it does not get uploaded as an artifact
    - rm -f cyber-dojo

    # Remove the new-ux repos so they dont get uploaded either
    - rm -rf commander
    - rm -rf starter
    - rm -rf web