services: docker
language: bash

addons:
  artifacts: true

script:
    - curl -O https://raw.githubusercontent.com/cyber-dojo/commander/master/cyber-dojo
    - chmod +x cyber-dojo

    # build the cyber-dojo/system-tests-environment image?
    #- cd system_test_environment
    #- ./build.sh
    #- cd ..

    - ./build.sh

    - ./build_new_ux_images.sh

    - URL=https://raw.githubusercontent.com/cyber-dojo/start-points-languages/master/languages_list_small
    - ./cyber-dojo start-point create small_langs --list=${URL}
    - ./build_fake_language_images.sh small_langs

    - URL=https://github.com/cyber-dojo/start-points-custom
    - ./cyber-dojo start-point create small_custom --git=${URL}
    - ./build_fake_language_images.sh small_custom

    # remove this dummy image...
    - docker rmi cyberdojofoundation/ruby_mini_test
    # so the real image gets pulled by...
    - ./cyber-dojo up --languages=small_langs --custom=small_custom

    - ./run_firefox_and_chrome_tests.sh

    # Remove the cyber-dojo script so it does not get uploaded as an artifact
    - rm -f cyber-dojo

    # Remove the new-ux repos so they dont get uploaded either
    - rm -rf commander
    - rm -rf starter
    - rm -rf web